In [1]:
import pandas as pd

df = pd.read_csv('data/r4n/dataset_r4n_c20_with_cid.csv')
df

,Num_c,SMILES,cid,iupac_name,molecular_weight,molecular_formula,complexity,rotatable_bond_count,heavy_atom_count,xlogp,Chloride_CAS,Bromide_CAS,Iodide_CAS,Fluoride_CAS
0,4,C[N+](C)(C)C,6380.0,tetramethylazanium,74.14,C4H12N+,19.0,0.0,5.0,0.3,"75-57-0, 200-880-8, 9050-97-9","64-20-0, 200-581-2","75-58-1, 200-881-3","373-68-2, 206-769-0, 99678-28-1"
1,5,CC[N+](C)(C)C,33993.0,ethyl(trimethyl)azanium,88.17,C5H14N+,33.0,1.0,6.0,0.6,NaN,2650-77-3,51-93-4,NaN
2,6,CCC[N+](C)(C)C,29385.0,trimethyl(propyl)azanium,102.20,C6H16N+,42.0,2.0,7.0,1.2,"2877-24-9, 608-246-6",NaN,19014-03-0,NaN
3,6,CC[N+](C)(C)CC,199517.0,diethyl(dimethyl)azanium,102.20,C6H16N+,42.0,2.0,7.0,1.0,"29508-45-0, 608-367-4",20109-38-0,4325-24-0,NaN
4,7,CC(C)C[N+](C)(C)C,15919129.0,trimethyl(2-methylpropyl)azanium,116.22,C7H18N+,59.0,2.0,8.0,1.6,NaN,79859-70-4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,20,CCCCCCC[N+](C)(CCCCCC)CCCCCC,175529579.0,heptyl-dihexyl-methylazanium,298.60,C20H44N+,188.0,16.0,21.0,7.8,NaN,NaN,NaN,NaN
361,20,CCCCCCC[N+](CCC)(CCC)CCCCCCC,87534339.0,diheptyl(dipropyl)azanium,298.60,C20H44N+,178.0,16.0,21.0,7.8,NaN,NaN,NaN,NaN
362,20,CCCCC[N+](CCC)(CCCCC)CCCCC(C)C,123559899.0,5-methylhexyl-dipentyl-propylazanium,298.60,C20H44N+,200.0,15.0,21.0,7.3,NaN,NaN,NaN,NaN
363,20,CCCCC[N+](CCCCC)(CCCCC)CCCCC,17249.0,tetrapentylazanium,298.60,C20H44N+,155.0,16.0,21.0,7.4,"4965-17-7, 225-606-4","866-97-7, 212-756-0","2498-20-6, 219-688-0",69468-58-2
364,20,CCCC[N+](CCCC)(CCCC)CCCCC(C)CC,161051619.0,tributyl(5-methylheptyl)azanium,298.60,C20H44N+,190.0,15.0,21.0,7.2,NaN,NaN,NaN,NaN

In [2]:
# 检查数据框结构和SMILES列
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Num_c                 365 non-null    int64
 1   SMILES                365 non-null    object
 2   cid                   365 non-null    float64
 3   iupac_name            365 non-null    object
 4   molecular_weight      365 non-null    float64
 5   molecular_formula     323 non-null    object
 6   complexity            323 non-null    float64
 7   rotatable_bond_count  323 non-null    float64
 8   heavy_atom_count      323 non-null    float64
 9   xlogp                 323 non-null    float64
 10  Chloride_CAS          49 non-null     object
 11  Bromide_CAS           64 non-null     object
 12  Iodide_CAS            40 non-null     object
 13  Fluoride_CAS          12 non-null     object
dtypes: float64(6), int64(1), object(7)
memory usage: 40.1+ KB

,Num_c,SMILES,cid,iupac_name,molecular_weight,molecular_formula,complexity,rotatable_bond_count,heavy_atom_count,xlogp,Chloride_CAS,Bromide_CAS,Iodide_CAS,Fluoride_CAS
0,4,C[N+](C)(C)C,6380.0,tetramethylazanium,74.14,C4H12N+,19.0,0.0,5.0,0.3,"75-57-0, 200-880-8, 9050-97-9","64-20-0, 200-581-2","75-58-1, 200-881-3","373-68-2, 206-769-0, 99678-28-1"
1,5,CC[N+](C)(C)C,33993.0,ethyl(trimethyl)azanium,88.17,C5H14N+,33.0,1.0,6.0,0.6,NaN,2650-77-3,51-93-4,NaN
2,6,CCC[N+](C)(C)C,29385.0,trimethyl(propyl)azanium,102.20,C6H16N+,42.0,2.0,7.0,1.2,"2877-24-9, 608-246-6",NaN,19014-03-0,NaN
3,6,CC[N+](C)(C)CC,199517.0,diethyl(dimethyl)azanium,102.20,C6H16N+,42.0,2.0,7.0,1.0,"29508-45-0, 608-367-4",20109-38-0,4325-24-0,NaN
4,7,CC(C)C[N+](C)(C)C,15919129.0,trimethyl(2-methylpropyl)azanium,116.22,C7H18N+,59.0,2.0,8.0,1.6,NaN,79859-70-4,NaN,NaN

In [3]:
import pubchempy as pcp
import time
from tqdm import tqdm

def get_xlogp_from_smiles(smiles):
    """通过SMILES从PubChem查询XLogP值"""
    try:
        compounds = pcp.get_compounds(smiles, namespace='smiles')
        if compounds:
            comp = compounds[0]
            # 获取XLogP属性
            xlogp = comp.xlogp
            return xlogp
        return None
    except Exception as e:
        print(f"Error for SMILES {smiles}: {e}")
        return None

# 创建新列存储从PubChem查询的XLogP
df['xlogp_pubchem'] = None

# 对每个SMILES查询XLogP（带进度条）
for idx in tqdm(df.index, desc="Querying PubChem"):
    smiles = df.loc[idx, 'SMILES']
    xlogp_value = get_xlogp_from_smiles(smiles)
    df.loc[idx, 'xlogp_pubchem'] = xlogp_value
    # 添加小延迟避免请求过快
    time.sleep(0.2)

print(f"\n完成查询！")
print(f"成功获取 {df['xlogp_pubchem'].notna().sum()} 个XLogP值")
print(f"缺失 {df['xlogp_pubchem'].isna().sum()} 个XLogP值")

Querying PubChem:  11%|█         | 40/365 [01:10<07:55,  1.46s/it]

Error for SMILES CCCCC(C)C[N+](C)(C)C: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1081)>

Querying PubChem: 100%|██████████| 365/365 [20:07<00:00,  3.31s/it]

完成查询！
成功获取 364 个XLogP值
缺失 1 个XLogP值

In [4]:
df

,Num_c,SMILES,cid,iupac_name,molecular_weight,molecular_formula,complexity,rotatable_bond_count,heavy_atom_count,xlogp,Chloride_CAS,Bromide_CAS,Iodide_CAS,Fluoride_CAS,xlogp_pubchem
0,4,C[N+](C)(C)C,6380.0,tetramethylazanium,74.14,C4H12N+,19.0,0.0,5.0,0.3,"75-57-0, 200-880-8, 9050-97-9","64-20-0, 200-581-2","75-58-1, 200-881-3","373-68-2, 206-769-0, 99678-28-1",0.3
1,5,CC[N+](C)(C)C,33993.0,ethyl(trimethyl)azanium,88.17,C5H14N+,33.0,1.0,6.0,0.6,NaN,2650-77-3,51-93-4,NaN,0.6
2,6,CCC[N+](C)(C)C,29385.0,trimethyl(propyl)azanium,102.20,C6H16N+,42.0,2.0,7.0,1.2,"2877-24-9, 608-246-6",NaN,19014-03-0,NaN,1.2
3,6,CC[N+](C)(C)CC,199517.0,diethyl(dimethyl)azanium,102.20,C6H16N+,42.0,2.0,7.0,1.0,"29508-45-0, 608-367-4",20109-38-0,4325-24-0,NaN,1
4,7,CC(C)C[N+](C)(C)C,15919129.0,trimethyl(2-methylpropyl)azanium,116.22,C7H18N+,59.0,2.0,8.0,1.6,NaN,79859-70-4,NaN,NaN,1.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,20,CCCCCCC[N+](C)(CCCCCC)CCCCCC,175529579.0,heptyl-dihexyl-methylazanium,298.60,C20H44N+,188.0,16.0,21.0,7.8,NaN,NaN,NaN,NaN,7.8
361,20,CCCCCCC[N+](CCC)(CCC)CCCCCCC,87534339.0,diheptyl(dipropyl)azanium,298.60,C20H44N+,178.0,16.0,21.0,7.8,NaN,NaN,NaN,NaN,7.8
362,20,CCCCC[N+](CCC)(CCCCC)CCCCC(C)C,123559899.0,5-methylhexyl-dipentyl-propylazanium,298.60,C20H44N+,200.0,15.0,21.0,7.3,NaN,NaN,NaN,NaN,7.3
363,20,CCCCC[N+](CCCCC)(CCCCC)CCCCC,17249.0,tetrapentylazanium,298.60,C20H44N+,155.0,16.0,21.0,7.4,"4965-17-7, 225-606-4","866-97-7, 212-756-0","2498-20-6, 219-688-0",69468-58-2,7.4
364,20,CCCC[N+](CCCC)(CCCC)CCCCC(C)CC,161051619.0,tributyl(5-methylheptyl)azanium,298.60,C20H44N+,190.0,15.0,21.0,7.2,NaN,NaN,NaN,NaN,7.2

In [5]:
# 重新查询缺失的XLogP值
missing_indices = df[df['xlogp_pubchem'].isna()].index
for idx in tqdm(missing_indices, desc="Re-querying missing XLogP"):
    smiles = df.loc[idx, 'SMILES']
    xlogp_value = get_xlogp_from_smiles(smiles)
    df.loc[idx, 'xlogp_pubchem'] = xlogp_value
    time.sleep(0.2)

print(f"\n重新查询完成！")
print(f"成功获取 {df['xlogp_pubchem'].notna().sum()} 个XLogP值")
print(f"缺失 {df['xlogp_pubchem'].isna().sum()} 个XLogP值")
df

Re-querying missing XLogP: 100%|██████████| 1/1 [00:01<00:00,  1.53s/it]

重新查询完成！
成功获取 365 个XLogP值
缺失 0 个XLogP值

,Num_c,SMILES,cid,iupac_name,molecular_weight,molecular_formula,complexity,rotatable_bond_count,heavy_atom_count,xlogp,Chloride_CAS,Bromide_CAS,Iodide_CAS,Fluoride_CAS,xlogp_pubchem
0,4,C[N+](C)(C)C,6380.0,tetramethylazanium,74.14,C4H12N+,19.0,0.0,5.0,0.3,"75-57-0, 200-880-8, 9050-97-9","64-20-0, 200-581-2","75-58-1, 200-881-3","373-68-2, 206-769-0, 99678-28-1",0.3
1,5,CC[N+](C)(C)C,33993.0,ethyl(trimethyl)azanium,88.17,C5H14N+,33.0,1.0,6.0,0.6,NaN,2650-77-3,51-93-4,NaN,0.6
2,6,CCC[N+](C)(C)C,29385.0,trimethyl(propyl)azanium,102.20,C6H16N+,42.0,2.0,7.0,1.2,"2877-24-9, 608-246-6",NaN,19014-03-0,NaN,1.2
3,6,CC[N+](C)(C)CC,199517.0,diethyl(dimethyl)azanium,102.20,C6H16N+,42.0,2.0,7.0,1.0,"29508-45-0, 608-367-4",20109-38-0,4325-24-0,NaN,1
4,7,CC(C)C[N+](C)(C)C,15919129.0,trimethyl(2-methylpropyl)azanium,116.22,C7H18N+,59.0,2.0,8.0,1.6,NaN,79859-70-4,NaN,NaN,1.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,20,CCCCCCC[N+](C)(CCCCCC)CCCCCC,175529579.0,heptyl-dihexyl-methylazanium,298.60,C20H44N+,188.0,16.0,21.0,7.8,NaN,NaN,NaN,NaN,7.8
361,20,CCCCCCC[N+](CCC)(CCC)CCCCCCC,87534339.0,diheptyl(dipropyl)azanium,298.60,C20H44N+,178.0,16.0,21.0,7.8,NaN,NaN,NaN,NaN,7.8
362,20,CCCCC[N+](CCC)(CCCCC)CCCCC(C)C,123559899.0,5-methylhexyl-dipentyl-propylazanium,298.60,C20H44N+,200.0,15.0,21.0,7.3,NaN,NaN,NaN,NaN,7.3
363,20,CCCCC[N+](CCCCC)(CCCCC)CCCCC,17249.0,tetrapentylazanium,298.60,C20H44N+,155.0,16.0,21.0,7.4,"4965-17-7, 225-606-4","866-97-7, 212-756-0","2498-20-6, 219-688-0",69468-58-2,7.4
364,20,CCCC[N+](CCCC)(CCCC)CCCCC(C)CC,161051619.0,tributyl(5-methylheptyl)azanium,298.60,C20H44N+,190.0,15.0,21.0,7.2,NaN,NaN,NaN,NaN,7.2

In [6]:
df.to_csv('data/r4n_gap_2.csv', index=False)